version: "3.8"

services:
  backend:
    image: juwono136/todolist-backend:latest
    restart: always
    environment:
      PORT: ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "3002:3002"

  frontend:
    image: juwono136/todolist-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"
